Add alt text to images on the homepage
chartjs/www.chartjs.org pull request #20
Opened 2023-04-18 20:54 UTC by julianna-langston

For this issue: https://github.com/chartjs/Chart.js/issues/11231

Adds alternative text to the images on the chart.js homepage.

2023-04-18 21:27 UTC, etimberg approved these changes

2023-04-18 22:35 UTC, LeeLenaleee requested changes
Would be better to have a description in all alt texts instead of having empty ones

2023-04-18 22:35 UTC, LeeLenaleee commented on src/templates/footer.html
> +	<img src="{{base_path}}/img/icon.svg" alt="" />
Logo grey scale would be a better fit as an empty alt text

2023-04-18 22:35 UTC, LeeLenaleee commented on src/templates/homepage.html
> +						<img src="./img/open-source.svg" alt="" />
Open source indicator icon

2023-04-18 22:35 UTC, LeeLenaleee commented on src/templates/homepage.html
> +						<img src="./img/chart-types.svg" alt="" />
Bar chart icon

2023-04-18 22:35 UTC, LeeLenaleee commented on src/templates/homepage.html
> +						<img src="./img/canvas-icon.svg" alt="" />
Html logo

2023-04-18 22:35 UTC, LeeLenaleee commented on src/templates/homepage.html
> +						<img src="./img/responsive.svg" alt="" />
Responsive icon

2023-04-18 23:21 UTC, julianna-ciq commented
I thought that those icons were all decorative. [Decorative images shouldn't have any alt text](https://www.w3.org/WAI/tutorials/images/decorative/), because it doesn't provide additional information to a screen reader user. For example, if we used the alt text "Responsive" for the icon above the text "Responsive", a screen reader will read that as:
> Responsive, graphic
> Responsive, heading level 4

In this case, the icon's alt text is redundant. 

If you consider the images to be *informative*, rather than decorative, I can certainly update the alt text.

2023-04-19 17:42 UTC, LeeLenaleee approved these changes

2023-04-19 18:52 UTC, merged